if(EXISTS "/home/runner/work/bison/bison/build_o0/tests/rmi_c_test[1]_tests.cmake")
  include("/home/runner/work/bison/bison/build_o0/tests/rmi_c_test[1]_tests.cmake")
else()
  add_test(rmi_c_test_NOT_BUILT rmi_c_test_NOT_BUILT)
endif()
