<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Bdg.Bison</RootNamespace>
    <AssemblyName>Bdg.Bison</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
